### ISSUE TITLE
setting up the app

### ISSUE THREAD

**Issue by cnaaq** [jaraco/wolframalpha#3]
Hi,

Could you please guide me with setting up the app and extracting lib folder from it? (There is no .sh file in the folder)

Thanks

**Comment by jaraco** [comment]
Hi. Thanks for your interest in the wolframalpha project.

I'm not sure what you seek to achieve by "extracting lib folder" from the project. This project is not an app, but is a Python client library for working with the Wolfram|Alpha service.

The README describes how to get started, but assumes some familiarity with Python. If you're not familiar with Python, you should still be able to simply clone the repo (or download and extract a zip file), and then run `python` from inside the repo to begin the simple tutorial laid out in the README.

**Comment by cnaaq** [comment]
Thank you for you reply.
I used Pycharm to query wolframalpha and I successfuly did it (just as described in README).
Now, I want to use it in Choregraphe (for NAO robot) and in order to say:
import wolframalpha
first I need to include the library in the program.
Sorry for the poor describing of the case but a similar example is the wikipedia package that is described in the link below:
https://github.com/sebcagnon/PepperWiki

**Comment by jaraco** [comment]
How cool. I have a NAO, and I've [developed for it before](https://github.com/jaraco/cherry-nao), but it's been a while.

If I recall, it's a little tricky getting a library (CherryPy in my case, wolframalpha in yours) to be visible to the NAO behavior.

Looking at the example you provided, I'll bet you could follow that pattern (copy the PepperWiki project to your own project) to create your behavior, and in the requirements.txt specify "wolframalpha" instead of "wikipedia".

I hope that helps. If you get something working do be sure to let me know. Or if you have more questions, feel free to follow up here.
