### ISSUE TITLE
Consider Adding License File

### ISSUE THREAD

**Issue by welchbj** [jaraco/wolframalpha#8]
Hi, I'm looking to use this library in a school project. It looks like this library is MIT Licensed based on setup.py, would you consider adding a note in the readme and a license file in the project's top-level directory, just for clarity's sake? I would be happy to make a PR if this is acceptable to you.

**Comment by jaraco** [comment]
The library is licensed under The OSI approved MIT license. The project metadata is the clearest single place to advertise that fact. A separate license file only adds complication and the potential for divergence. If a license file is necessary or desirable, it should go in /jaraco/skeleton from which this project and dozens others derive their structure... But I'm not even sure I would want to add the complication there. I really wish the community would devise a common practice for a project to _elect_ a license rather than. The current expectation that each and. Every project should paste one.

**Comment by welchbj** [comment]
Now that you mention it, I guess it would be better to have a single source of truth for the license. I've just been following the trend I've seen in the Python community (field in setup.py, license file, and readme badge).
